// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GlobalDb.Models;

public partial class AppConfiguration
{
    public string AppConfigurationId { get; set; }

    public string FileKey { get; set; }

    public string FileName { get; set; }

    public string Title { get; set; }

    public string Version { get; set; }

    public string Url { get; set; }

    public string Etag { get; set; }

    public long? LastModified { get; set; }

    public int? Size { get; set; }

    public string BucketName { get; set; }

    public string AppName { get; set; }

    public string ConfigurationIconPath { get; set; }

    public string Comments { get; set; }

    public int? InheritStyles { get; set; }

    public string CurrentlyInstalledVersion { get; set; }

    public string CurrentlyInstalledVersionLabel { get; set; }

    public int? IsScheduledForDeletion { get; set; }

    public int? HasBooted { get; set; }

    public int? UsingExternalStorage { get; set; }

    public int? IsInitializationSelectionConfiguration { get; set; }

    public int? RetainViewedProgressOnConfigurationUpdate { get; set; }

    public int? IsActionCancelable { get; set; }

    public int? IsExpanded { get; set; }
}