// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GlobalDb.Models;

public partial class CommandCoin
{
    public string CoinId { get; set; }

    public string CoinDate { get; set; }

    public string CoinOccasion { get; set; }

    public string CoinRecipient { get; set; }

    public string CoinJustification { get; set; }

    public string CoinType { get; set; }
}