// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GlobalDb.Models;

public partial class FormValue
{
    public string FormValueId { get; set; }

    public string FormInstanceId { get; set; }

    public string QuestionId { get; set; }

    public string Value { get; set; }

    public string Type { get; set; }
}